---
language: go

env:
  global:
    - CGO_CFLAGS="-I$HOME/hashcat/deps/OpenCL-Headers -I$HOME/hashcat/include"
    - CGO_LDFLAGS="-L$HOME/hashcat"
    - LD_LIBRARY_PATH="/home/travis/hashcat:$LD_LIBRARY_PATH"
    - HASHCAT_VERSION="v3.6.0"

addons:
 apt:
  packages:
    - ocl-icd-opencl-dev

before_install:
  - ./misc/setup_travis.sh

go:
  - 1.9.x
  - tip

script:
  - make test