---
language: go
addons:
 apt:
  packages:
    - ocl-icd-opencl-dev

before_install:
  - ./setup_travis.sh

go:
  - 1.9.x

script:
  - CGO_CFLAGS="-I/home/travis/hashcat/deps/OpenCL-Headers -I/home/travis/hashcat/include" CGO_LDFLAGS="-L/home/travis/hashcat" make test